export default function Day18TestingTasks() {
  return {
    tasks: [
      {
        text: 'Какая агрегатная функция считает количество строк?',
        type: 'choice',
        answer: 'count',
        options: ['count', 'sum', 'total', 'number'],
        hint: 'SELECT COUNT(*) FROM users',
        difficulty: 'Легко',
      },
      {
        text: 'Какая функция вычисляет среднее значение?',
        type: 'choice',
        answer: 'avg',
        options: ['avg', 'mean', 'middle', 'sum'],
        hint: 'AVG(age) — average',
        difficulty: 'Легко',
      },
      {
        text: 'Если возрасты пользователей 25, 31, 19, 42, 28 — что вернёт MAX(age)?',
        type: 'input',
        answer: '42',
        hint: 'MAX возвращает наибольшее значение',
        difficulty: 'Легко',
      },
      {
        text: 'Какое ключевое слово группирует строки по одинаковому значению?',
        type: 'choice',
        answer: 'group by',
        options: ['group by', 'order by', 'having', 'union'],
        hint: 'GROUP BY city — группировка по городу',
        difficulty: 'Средне',
      },
      {
        text: 'Чем HAVING отличается от WHERE?',
        type: 'choice',
        answer: 'фильтрует группы',
        options: ['фильтрует группы', 'фильтрует строки', 'сортирует', 'соединяет таблицы'],
        hint: 'WHERE — до группировки (строки), HAVING — после (группы)',
        difficulty: 'Сложно',
      },
      {
        text: 'Какая команда добавляет новую строку в таблицу?',
        type: 'choice',
        answer: 'insert',
        options: ['insert', 'add', 'create', 'append'],
        hint: 'INSERT INTO users VALUES (...)',
        difficulty: 'Легко',
      },
      {
        text: 'Какая команда изменяет существующие данные?',
        type: 'choice',
        answer: 'update',
        options: ['update', 'change', 'modify', 'set'],
        hint: 'UPDATE users SET city = ... WHERE id = ...',
        difficulty: 'Средне',
      },
      {
        text: 'Какая команда удаляет строки из таблицы?',
        type: 'choice',
        answer: 'delete',
        options: ['delete', 'remove', 'drop', 'clear'],
        hint: 'DELETE FROM users WHERE id = 6',
        difficulty: 'Средне',
      },
      {
        text: 'Что обязательно нужно писать в UPDATE и DELETE, чтобы не затронуть все строки?',
        type: 'choice',
        answer: 'where',
        options: ['where', 'limit', 'having', 'select'],
        hint: 'Без WHERE команда изменит/удалит ВСЕ строки!',
        difficulty: 'Средне',
      },
      {
        text: 'Какая функция вернёт сумму всех значений в колонке?',
        type: 'choice',
        answer: 'sum',
        options: ['sum', 'count', 'total', 'add'],
        hint: 'SUM(price) — сумма цен',
        difficulty: 'Легко',
      },
    ],
  }
}
