export default function Day16LanguagesTasks() {
  return {
    tasks: [
      {
        text: 'Какой язык стал де-факто стандартом в продакшене как типизированная надстройка над JavaScript?',
        type: 'choice',
        answer: 'typescript',
        options: ['typescript', 'coffeescript', 'dart', 'python'],
        hint: 'Добавляет типы к JS',
        difficulty: 'Легко',
      },
      {
        text: 'Какой фреймворк построен поверх React и добавляет серверный рендеринг (SSR) от компании Vercel?',
        type: 'choice',
        answer: 'next.js',
        options: ['next.js', 'vue.js', 'svelte', 'astro'],
        hint: 'SSR, SSG, маршрутизация из коробки',
        difficulty: 'Средне',
      },
      {
        text: 'Какой быстрый сборщик проектов заменяет Webpack в большинстве новых проектов?',
        type: 'choice',
        answer: 'vite',
        options: ['vite', 'gulp', 'parcel', 'rollup'],
        hint: 'Совпадает с итальянским словом «быстро»',
        difficulty: 'Средне',
      },
      {
        text: 'Какой Python-фреймворк с автоматической документацией (OpenAPI) стал популярным для REST API?',
        type: 'choice',
        answer: 'fastapi',
        options: ['fastapi', 'django', 'flask', 'tornado'],
        hint: 'Современный, высокопроизводительный',
        difficulty: 'Средне',
      },
      {
        text: 'Какой язык от Google создан для высоконагруженных систем и микросервисов?',
        type: 'choice',
        answer: 'go',
        options: ['go', 'rust', 'kotlin', 'ruby'],
        hint: 'Также называется Golang',
        difficulty: 'Легко',
      },
      {
        text: 'Какая реляционная БД является стандартом для большинства проектов?',
        type: 'choice',
        answer: 'postgresql',
        options: ['postgresql', 'mongodb', 'redis', 'clickhouse'],
        hint: 'Реляционная, не NoSQL',
        difficulty: 'Средне',
      },
      {
        text: 'Какая библиотека Python — основная для работы с табличными данными в аналитике?',
        type: 'choice',
        answer: 'pandas',
        options: ['pandas', 'numpy', 'matplotlib', 'requests'],
        hint: 'Названа в честь "panel data"',
        difficulty: 'Средне',
      },
      {
        text: 'Какой Deep Learning фреймворк доминирует для исследований и продакшена в 2026?',
        type: 'choice',
        answer: 'pytorch',
        options: ['pytorch', 'tensorflow', 'keras', 'jax'],
        hint: 'Разработан Meta, гибкий и питоновский',
        difficulty: 'Средне',
      },
      {
        text: 'Какой инструмент контейнеризации решает проблему «у меня работает, а на сервере нет»?',
        type: 'choice',
        answer: 'docker',
        options: ['docker', 'kubernetes', 'vagrant', 'ansible'],
        hint: 'Упаковывает приложение со всеми зависимостями',
        difficulty: 'Легко',
      },
      {
        text: 'Какая система контроля версий является абсолютным стандартом для командной работы?',
        type: 'choice',
        answer: 'git',
        options: ['git', 'svn', 'mercurial', 'perforce'],
        hint: 'GitHub, GitLab построены вокруг него',
        difficulty: 'Легко',
      },
    ],
  }
}
