export default function Day24PatternsTasks() {
  return {
    tasks: [
      {
        text: 'Two Pointers. Дан отсортированный массив [1, 3, 5, 7, 9] и target = 10. Какая пара даёт сумму 10? (левый + правый указатель)',
        type: 'choice',
        answer: '1 и 9',
        options: ['1 и 9', '3 и 7', '1 и 7', '3 и 9'],
        hint: 'left=0 (arr[0]=1), right=4 (arr[4]=9). 1+9=10 — нашли с первой итерации!',
        difficulty: 'Легко',
      },
      {
        text: 'Fast & Slow (цикл). В связном списке 1→2→3→4→2 (4 ведёт обратно к 2). Slow делает 1 шаг, fast — 2 шага за итерацию. На каком узле они встретятся?',
        type: 'choice',
        answer: '4',
        options: ['2', '3', '4', 'не встретятся'],
        hint: 'Трассируй: iter1: slow=2,fast=3 | iter2: slow=3,fast=2 (4→2) | iter3: slow=4,fast=4 — встреча!',
        difficulty: 'Средне',
      },
      {
        text: 'Fast & Slow (середина). Список из 5 узлов [1→2→3→4→5]. Slow +1 шаг, fast +2 шага, пока fast.next существует. Где остановится slow?',
        type: 'choice',
        answer: '3',
        options: ['2', '3', '4', '5'],
        hint: 'iter1: slow=2,fast=3 | iter2: slow=3,fast=5 | fast.next=None → стоп. slow=3 — это середина.',
        difficulty: 'Средне',
      },
      {
        text: 'Sliding Window. Массив [2, 1, 5, 1, 3, 2], размер окна k=3. Какая максимальная сумма подмассива размера 3?',
        type: 'choice',
        answer: '9',
        options: ['7', '8', '9', '10'],
        hint: 'Суммы окон: [2,1,5]=8, [1,5,1]=7, [5,1,3]=9, [1,3,2]=6. Максимум = 9.',
        difficulty: 'Легко',
      },
      {
        text: 'Бинарный поиск. Массив [1, 3, 5, 7, 9, 11], target=7. Какой индекс (0-based) вернёт бинарный поиск?',
        type: 'choice',
        answer: '3',
        options: ['2', '3', '4', '5'],
        hint: 'mid=2 (arr=5)<7 → lo=3; mid=4 (arr=9)>7 → hi=3; mid=3 (arr=7)=target → возврат 3.',
        difficulty: 'Легко',
      },
      {
        text: 'ДП: Числа Фибоначчи. dp[0]=0, dp[1]=1, dp[i]=dp[i-1]+dp[i-2]. Чему равно dp[7]?',
        type: 'choice',
        answer: '13',
        options: ['8', '11', '13', '21'],
        hint: 'Последовательность: 0,1,1,2,3,5,8,13 — dp[7]=13.',
        difficulty: 'Легко',
      },
      {
        text: 'ДП: Подъём по лестнице (Climbing Stairs). Можно делать 1 или 2 шага. Сколько способов подняться на 4 ступеньки?',
        type: 'choice',
        answer: '5',
        options: ['3', '4', '5', '6'],
        hint: 'dp[1]=1, dp[2]=2, dp[3]=3, dp[4]=dp[3]+dp[2]=5. Аналог Фибоначчи!',
        difficulty: 'Средне',
      },
      {
        text: 'ДП: Размен монет (Coin Change). Монеты [1, 3, 4], нужно набрать сумму 7. Минимальное количество монет?',
        type: 'choice',
        answer: '2',
        options: ['2', '3', '4', '7'],
        hint: 'dp[7]: используем 3+4=7 → 2 монеты. Это лучше, чем 1+3+3=7 (3 монеты).',
        difficulty: 'Сложно',
      },
    ],
  }
}
