export default function Day17TrendsTasks() {
  return {
    tasks: [
      {
        text: 'Какая SQL-команда выбирает данные из таблицы?',
        type: 'choice',
        answer: 'select',
        options: ['select', 'get', 'fetch', 'find'],
        hint: 'SELECT * FROM users',
        difficulty: 'Легко',
      },
      {
        text: 'Какое ключевое слово фильтрует строки по условию?',
        type: 'choice',
        answer: 'where',
        options: ['where', 'filter', 'having', 'if'],
        hint: 'SELECT * FROM users WHERE age > 18',
        difficulty: 'Легко',
      },
      {
        text: 'Что выберет запрос: SELECT * FROM users — сколько колонок вернётся, если в таблице 4 колонки?',
        type: 'input',
        answer: '4',
        hint: 'Звёздочка * означает «все колонки»',
        difficulty: 'Легко',
      },
      {
        text: 'Какое ключевое слово сортирует результат?',
        type: 'choice',
        answer: 'order by',
        options: ['order by', 'sort', 'group by', 'arrange'],
        hint: 'ORDER BY age DESC',
        difficulty: 'Средне',
      },
      {
        text: 'Что означает DESC в ORDER BY?',
        type: 'choice',
        answer: 'по убыванию',
        options: ['по убыванию', 'по возрастанию', 'описание', 'удалить'],
        hint: 'descending — от большего к меньшему',
        difficulty: 'Средне',
      },
      {
        text: 'Какой оператор проверяет вхождение в список: WHERE city ___ (\'Москва\', \'Сочи\')?',
        type: 'choice',
        answer: 'in',
        options: ['in', 'has', 'contains', 'between'],
        hint: 'WHERE city IN (...)',
        difficulty: 'Средне',
      },
      {
        text: 'Какой оператор ищет по шаблону, например имена на букву А: WHERE name ___ \'А%\'?',
        type: 'choice',
        answer: 'like',
        options: ['like', 'match', 'similar', 'equals'],
        hint: 'LIKE с символом % (любые символы)',
        difficulty: 'Средне',
      },
      {
        text: 'Какое ключевое слово оставляет только уникальные значения?',
        type: 'choice',
        answer: 'distinct',
        options: ['distinct', 'unique', 'group', 'only'],
        hint: 'SELECT DISTINCT city FROM users',
        difficulty: 'Средне',
      },
      {
        text: 'Какое ключевое слово ограничивает количество строк в результате?',
        type: 'choice',
        answer: 'limit',
        options: ['limit', 'top', 'max', 'count'],
        hint: 'ORDER BY age DESC LIMIT 3 — топ-3',
        difficulty: 'Средне',
      },
      {
        text: 'Что означает аббревиатура SQL?',
        type: 'choice',
        answer: 'structured query language',
        options: ['structured query language', 'simple question logic', 'system quality level', 'standard query link'],
        hint: 'Язык структурированных запросов',
        difficulty: 'Легко',
      },
    ],
  }
}
