export default function Day19SqlTasks() {
  return {
    tasks: [
      {
        text: 'Как называется уникальный идентификатор строки в таблице?',
        type: 'choice',
        answer: 'первичный ключ',
        options: ['первичный ключ', 'внешний ключ', 'индекс', 'хеш'],
        hint: 'PRIMARY KEY — уникален для каждой строки',
        difficulty: 'Легко',
      },
      {
        text: 'Как называется поле, которое ссылается на первичный ключ другой таблицы?',
        type: 'choice',
        answer: 'внешний ключ',
        options: ['внешний ключ', 'первичный ключ', 'связь', 'указатель'],
        hint: 'FOREIGN KEY связывает таблицы',
        difficulty: 'Средне',
      },
      {
        text: 'Какая команда соединяет две таблицы?',
        type: 'choice',
        answer: 'join',
        options: ['join', 'merge', 'connect', 'union'],
        hint: 'SELECT ... FROM a JOIN b ON ...',
        difficulty: 'Легко',
      },
      {
        text: 'Какой JOIN возвращает только строки с совпадением в обеих таблицах?',
        type: 'choice',
        answer: 'inner join',
        options: ['inner join', 'left join', 'right join', 'full join'],
        hint: 'INNER — только пересечение',
        difficulty: 'Средне',
      },
      {
        text: 'Какой JOIN вернёт ВСЕ строки из левой таблицы, даже без совпадений справа?',
        type: 'choice',
        answer: 'left join',
        options: ['left join', 'inner join', 'right join', 'cross join'],
        hint: 'LEFT JOIN — все слева + NULL где нет пары',
        difficulty: 'Средне',
      },
      {
        text: 'Что окажется в колонке справа при LEFT JOIN, если совпадения нет?',
        type: 'choice',
        answer: 'null',
        options: ['null', '0', 'пустая строка', 'ошибка'],
        hint: 'Пустое значение — NULL',
        difficulty: 'Средне',
      },
      {
        text: 'Как называется разбиение данных на таблицы для устранения дублирования?',
        type: 'choice',
        answer: 'нормализация',
        options: ['нормализация', 'индексация', 'агрегация', 'репликация'],
        hint: 'Чтобы менять данные в одном месте',
        difficulty: 'Сложно',
      },
      {
        text: 'Какая из этих баз данных — NoSQL?',
        type: 'choice',
        answer: 'mongodb',
        options: ['mongodb', 'postgresql', 'mysql', 'sqlite'],
        hint: 'Документо-ориентированная БД',
        difficulty: 'Средне',
      },
      {
        text: 'Запрос JOIN + GROUP BY + SUM(price) посчитает...',
        type: 'choice',
        answer: 'сумму по каждому пользователю',
        options: ['сумму по каждому пользователю', 'все заказы', 'одного пользователя', 'количество таблиц'],
        hint: 'Соединяем таблицы и группируем по пользователю',
        difficulty: 'Сложно',
      },
      {
        text: 'Когда лучше выбрать SQL, а не NoSQL?',
        type: 'choice',
        answer: 'когда важны связи и структура',
        options: ['когда важны связи и структура', 'когда нужна максимальная гибкость', 'для кэша', 'для логов'],
        hint: 'Банк, магазин — структурированные данные со связями',
        difficulty: 'Средне',
      },
    ],
  }
}
