export default function Day11GitTasks() {
  return {
    tasks: [
      {
        text: 'Что такое Git?',
        type: 'choice',
        answer: 'система контроля версий для отслеживания изменений в коде',
        options: ['язык программирования', 'система контроля версий для отслеживания изменений в коде', 'текстовый редактор', 'база данных'],
        hint: 'Git помогает сохранять историю и работать в команде',
        difficulty: 'Легко',
      },
      {
        text: 'Какая команда инициализирует новый репозиторий?',
        type: 'choice',
        answer: 'git init',
        options: ['git start', 'git init', 'git create', 'git new'],
        hint: 'Первая команда когда начинаешь новый проект',
        difficulty: 'Легко',
      },
      {
        text: 'Как добавить все изменённые файлы в staging area?',
        type: 'choice',
        answer: 'git add .',
        options: ['git add all', 'git add .', 'git stage', 'git commit all'],
        hint: 'Точка означает все файлы в текущей директории',
        difficulty: 'Легко',
      },
      {
        text: 'Какая команда создаёт новый коммит?',
        type: 'choice',
        answer: 'git commit -m "сообщение"',
        options: ['git save', 'git commit -m "сообщение"', 'git log', 'git push'],
        hint: '-m флаг нужен для написания описания',
        difficulty: 'Легко',
      },
      {
        text: 'Как создать новую ветку и переключиться на неё одной командой?',
        type: 'choice',
        answer: 'git checkout -b имя-ветки',
        options: ['git branch имя-ветки', 'git checkout -b имя-ветки', 'git new-branch', 'git create-branch'],
        hint: '-b флаг создаёт ветку и переключается',
        difficulty: 'Средне',
      },
      {
        text: 'Какая команда отправляет коммиты на удалённый сервер?',
        type: 'choice',
        answer: 'git push',
        options: ['git send', 'git push', 'git upload', 'git sync'],
        hint: 'Это загруза твоих изменений на GitHub/GitLab',
        difficulty: 'Средне',
      },
      {
        text: 'Что такое Pull Request (PR)?',
        type: 'choice',
        answer: 'предложение своих изменений для рассмотрения перед включением в главный код',
        options: ['команда git', 'способ скачать код', 'предложение своих изменений для рассмотрения перед включением в главный код', 'тип файла'],
        hint: 'Это как бы просишь: посмотри мой код, он хороший?',
        difficulty: 'Средне',
      },
      {
        text: 'Какая команда показывает историю коммитов?',
        type: 'choice',
        answer: 'git log',
        options: ['git history', 'git log', 'git commits', 'git timeline'],
        hint: 'log отображает все сохранённые коммиты',
        difficulty: 'Средне',
      },
      {
        text: 'Какая платформа для хостинга репозиториев самая популярная?',
        type: 'choice',
        answer: 'GitHub',
        options: ['GitLab', 'GitHub', 'Bitbucket', 'Gitea'],
        hint: 'Самая популярная, принадлежит Microsoft',
        difficulty: 'Легко',
      },
      {
        text: 'Как скачать обновления с удалённого репозитория?',
        type: 'choice',
        answer: 'git pull',
        options: ['git download', 'git pull', 'git fetch all', 'git sync'],
        hint: 'pull = fetch + merge (скачивает и объединяет)',
        difficulty: 'Средне',
      },
    ],
  }
}
