export default function July1PythonTasks() {
  return {
    tasks: [
      {
        text: 'Что выведет код?\n\nx = 7 // 2\nprint(x)',
        type: 'choice',
        answer: '3',
        options: ['3', '3.5', '4', '2'],
        hint: '// — целочисленное деление, отбрасывает дробную часть',
        difficulty: 'Легко',
      },
      {
        text: 'Какой тип данных у значения True?',
        type: 'choice',
        answer: 'bool',
        options: ['bool', 'int', 'str', 'None'],
        hint: 'True и False — логические значения',
        difficulty: 'Легко',
      },
      {
        text: 'Что выведет код?\n\ns = "Python"\nprint(s[1:4])',
        type: 'choice',
        answer: 'yth',
        options: ['yth', 'Pyt', 'ytho', 'yt'],
        hint: 'Срез [1:4] — символы с индекса 1 по 3 включительно',
        difficulty: 'Средне',
      },
      {
        text: 'Какой метод добавляет элемент в конец списка?',
        type: 'choice',
        answer: 'append()',
        options: ['append()', 'add()', 'insert()', 'push()'],
        hint: 'add() — для множеств, push() в Python нет',
        difficulty: 'Легко',
      },
      {
        text: 'Что выведет код?\n\nfor i in range(1, 6, 2):\n    print(i, end=" ")',
        type: 'choice',
        answer: '1 3 5',
        options: ['1 3 5', '1 2 3 4 5', '2 4', '1 3 5 7'],
        hint: 'range(start, stop, step): от 1 до 5 с шагом 2',
        difficulty: 'Средне',
      },
      {
        text: 'Как получить значение по ключу "age" из словаря d безопасно (без ошибки, если ключа нет)?',
        type: 'choice',
        answer: 'd.get("age")',
        options: ['d.get("age")', 'd["age"]', 'd.age', 'd.find("age")'],
        hint: 'd["age"] выбросит KeyError, если ключа нет; get вернёт None',
        difficulty: 'Средне',
      },
      {
        text: 'Что выведет код?\n\nprint(len("hello"))',
        type: 'choice',
        answer: '5',
        options: ['5', '4', '6', 'hello'],
        hint: 'len() возвращает количество символов',
        difficulty: 'Легко',
      },
      {
        text: 'Что выведет код?\n\nnums = [1, 2, 3]\nprint([x * 2 for x in nums])',
        type: 'choice',
        answer: '[2, 4, 6]',
        options: ['[2, 4, 6]', '[1, 2, 3, 1, 2, 3]', '[1, 4, 9]', '[2, 4, 6, 8]'],
        hint: 'List comprehension умножает каждый элемент на 2',
        difficulty: 'Средне',
      },
      {
        text: 'Какой результат выражения?\n\nprint(3 == 3.0)',
        type: 'choice',
        answer: 'True',
        options: ['True', 'False', 'Ошибка', 'None'],
        hint: 'По значению int 3 и float 3.0 равны',
        difficulty: 'Средне',
      },
      {
        text: 'Что выведет код?\n\nx = 5\nif x > 10:\n    print("A")\nelif x > 3:\n    print("B")\nelse:\n    print("C")',
        type: 'choice',
        answer: 'B',
        options: ['B', 'A', 'C', 'A B'],
        hint: 'x=5: первое условие ложно, второе (x>3) истинно',
        difficulty: 'Легко',
      },
    ],
  }
}
