export default function July1BackendTasks() {
  return {
    tasks: [
      {
        text: 'Какой тип типизации у языка Go?',
        type: 'choice',
        answer: 'Статическая',
        options: ['Статическая', 'Динамическая', 'Отсутствует', 'Только во время выполнения'],
        hint: 'Типы проверяются на этапе компиляции',
        difficulty: 'Легко',
      },
      {
        text: 'Как в Go называются лёгкие «потоки» для параллельного выполнения?',
        type: 'choice',
        answer: 'Горутины (goroutines)',
        options: ['Горутины (goroutines)', 'Треды (threads)', 'Корутины Python', 'Воркеры'],
        hint: 'Запускаются ключевым словом go',
        difficulty: 'Средне',
      },
      {
        text: 'Какой Python-фреймворк даёт авто-документацию OpenAPI и построен на type hints?',
        type: 'choice',
        answer: 'FastAPI',
        options: ['FastAPI', 'Django', 'Flask', 'Gin'],
        hint: 'Современный async-фреймворк, документация по /docs',
        difficulty: 'Средне',
      },
      {
        text: 'Какой фреймворк Python — full-stack «всё из коробки» (ORM, админка)?',
        type: 'choice',
        answer: 'Django',
        options: ['Django', 'Flask', 'FastAPI', 'Echo'],
        hint: 'Для крупных проектов с готовой админкой',
        difficulty: 'Легко',
      },
      {
        text: 'Какой из фреймворков относится к Go?',
        type: 'choice',
        answer: 'Gin',
        options: ['Gin', 'Flask', 'Django', 'FastAPI'],
        hint: 'Самый популярный веб-фреймворк Go',
        difficulty: 'Средне',
      },
      {
        text: 'Что из этого — сильная сторона Go по сравнению с Python?',
        type: 'choice',
        answer: 'Скорость выполнения и параллелизм',
        options: [
          'Скорость выполнения и параллелизм',
          'Больше библиотек для ML',
          'Динамическая типизация',
          'Проще синтаксис для новичка',
        ],
        hint: 'Go компилируется и создавался для высоких нагрузок',
        difficulty: 'Средне',
      },
      {
        text: 'Как Python исполняет код?',
        type: 'choice',
        answer: 'Интерпретируется',
        options: ['Интерпретируется', 'Компилируется в бинарник', 'Транслируется в Go', 'Выполняется в браузере'],
        hint: 'В отличие от Go, который компилируется',
        difficulty: 'Легко',
      },
      {
        text: 'Что аббревиатура GIL в Python ограничивает?',
        type: 'choice',
        answer: 'Параллельное выполнение потоков',
        options: [
          'Параллельное выполнение потоков',
          'Размер переменных',
          'Количество библиотек',
          'Длину кода',
        ],
        hint: 'Global Interpreter Lock мешает истинной многопоточности',
        difficulty: 'Сложно',
      },
      {
        text: 'Какой стандартный пакет Go позволяет поднять HTTP-сервер без сторонних библиотек?',
        type: 'choice',
        answer: 'net/http',
        options: ['net/http', 'http.server', 'express', 'requests'],
        hint: 'Встроен в стандартную библиотеку Go',
        difficulty: 'Средне',
      },
      {
        text: 'Для какой задачи Python подходит лучше, чем Go?',
        type: 'choice',
        answer: 'Machine Learning и анализ данных',
        options: [
          'Machine Learning и анализ данных',
          'Высоконагруженные микросервисы',
          'Системное программирование',
          'Компиляция в один бинарник',
        ],
        hint: 'Экосистема Python (pandas, scikit-learn) — стандарт в data science',
        difficulty: 'Легко',
      },
    ],
  }
}
