export default function July5PandasTasks() {
  return {
    tasks: [
      {
        text: 'Что произойдёт, если изменить срез массива NumPy: part = a[1:4]; part[0] = 99?',
        type: 'choice',
        answer: 'Изменится и исходный массив a, потому что срез — это view (окно в ту же память)',
        options: [
          'Ничего, срез всегда независимая копия',
          'Изменится и исходный массив a, потому что срез — это view (окно в ту же память)',
          'NumPy выдаст ошибку',
          'Массив a удалится',
        ],
        hint: 'Чтобы получить независимую копию, нужен .copy()',
        difficulty: 'Сложно',
      },
      {
        text: 'Что делает np.where(a >= 10, "много", "мало")?',
        type: 'choice',
        answer: 'Для каждого элемента возвращает "много", если условие истинно, иначе "мало"',
        options: [
          'Удаляет элементы больше 10',
          'Для каждого элемента возвращает "много", если условие истинно, иначе "мало"',
          'Сортирует массив',
          'Считает количество элементов ≥ 10',
        ],
        hint: 'Векторизованный аналог if/else',
        difficulty: 'Средне',
      },
      {
        text: 'Что вернёт np.argsort(np.array([30, 10, 20]))?',
        type: 'choice',
        answer: '[1 2 0] — индексы элементов в порядке сортировки',
        options: [
          '[10 20 30]',
          '[1 2 0] — индексы элементов в порядке сортировки',
          '[30 20 10]',
          '[0 1 2]',
        ],
        hint: 'argsort возвращает индексы, а не сами значения',
        difficulty: 'Сложно',
      },
      {
        text: 'Как посчитать сумму массива, игнорируя пропуски np.nan?',
        type: 'choice',
        answer: 'np.nansum(a)',
        options: ['a.sum()', 'np.nansum(a)', 'a.total()', 'np.ignore(a)'],
        hint: 'Обычный sum() вернёт nan; есть специальные nan-версии функций',
        difficulty: 'Средне',
      },
      {
        text: 'Какие две основные структуры данных даёт pandas?',
        type: 'choice',
        answer: 'Series (колонка) и DataFrame (таблица)',
        options: [
          'List и Dict',
          'Series (колонка) и DataFrame (таблица)',
          'Array и Matrix',
          'Row и Column',
        ],
        hint: 'Одномерная и двумерная структуры',
        difficulty: 'Легко',
      },
      {
        text: 'Какой функцией обычно загружают таблицу из CSV-файла в pandas?',
        type: 'choice',
        answer: 'pd.read_csv("data.csv")',
        options: [
          'pd.open("data.csv")',
          'pd.read_csv("data.csv")',
          'pd.load("data.csv")',
          'pd.import_csv("data.csv")',
        ],
        hint: 'read_ + формат файла',
        difficulty: 'Легко',
      },
      {
        text: 'В чём разница между loc и iloc в pandas?',
        type: 'choice',
        answer: 'loc обращается по меткам (именам), iloc — по числовым позициям',
        options: [
          'Это одно и то же',
          'loc обращается по меткам (именам), iloc — по числовым позициям',
          'loc для колонок, iloc для строк',
          'loc быстрее, iloc медленнее',
        ],
        hint: 'i в iloc — от integer (число)',
        difficulty: 'Средне',
      },
      {
        text: 'Что вернёт df[df["age"] > 25]?',
        type: 'choice',
        answer: 'Строки таблицы, где значение в колонке age больше 25',
        options: [
          'Число строк, где age больше 25',
          'Строки таблицы, где значение в колонке age больше 25',
          'Колонку age целиком',
          'Ошибку',
        ],
        hint: 'Булева индексация, как в NumPy',
        difficulty: 'Средне',
      },
      {
        text: 'Что делает df.groupby("city")["salary"].mean()?',
        type: 'choice',
        answer: 'Считает среднюю зарплату отдельно по каждому городу',
        options: [
          'Считает среднюю зарплату по всей таблице',
          'Считает среднюю зарплату отдельно по каждому городу',
          'Сортирует таблицу по городам',
          'Удаляет колонку city',
        ],
        hint: 'Принцип split → apply → combine',
        difficulty: 'Средне',
      },
      {
        text: 'Как в pandas заполнить пропущенные значения (NaN) нулём?',
        type: 'choice',
        answer: 'df.fillna(0)',
        options: ['df.dropna(0)', 'df.fillna(0)', 'df.replace_nan(0)', 'df.clean(0)'],
        hint: 'fill = заполнить, na = пропуски',
        difficulty: 'Средне',
      },
    ],
  }
}
