export default function July2CssTasks() {
  return {
    tasks: [
      {
        text: 'Какой селектор имеет более высокую специфичность?',
        type: 'choice',
        answer: '#header (id)',
        options: ['.header (класс)', 'header (тег)', '#header (id)', '* (универсальный)'],
        hint: 'id сильнее класса, класс сильнее тега',
        difficulty: 'Средне',
      },
      {
        text: 'Что делает box-sizing: border-box?',
        type: 'choice',
        answer: 'padding и border включаются в заданную width, не увеличивая итоговый размер',
        options: [
          'Убирает границы у всех блоков',
          'padding и border включаются в заданную width, не увеличивая итоговый размер',
          'Делает блок круглым',
          'Отключает отступы margin',
        ],
        hint: 'По умолчанию padding/border добавляются сверх width',
        difficulty: 'Средне',
      },
      {
        text: 'Какая единица измерения зависит от размера шрифта корневого элемента (html)?',
        type: 'choice',
        answer: 'rem',
        options: ['px', 'em', 'rem', 'vh'],
        hint: 'em зависит от родителя, rem — от html',
        difficulty: 'Средне',
      },
      {
        text: 'Какое значение display НЕ позволяет задавать width и height элементу?',
        type: 'choice',
        answer: 'inline',
        options: ['block', 'inline', 'inline-block', 'flex'],
        hint: 'inline подстраивается под содержимое',
        difficulty: 'Легко',
      },
      {
        text: 'Какое свойство Flexbox распределяет элементы с равными промежутками между ними, прижимая крайние к краям?',
        type: 'choice',
        answer: 'justify-content: space-between',
        options: [
          'align-items: center',
          'justify-content: space-between',
          'flex-wrap: wrap',
          'gap: 10px',
        ],
        hint: 'Крайние элементы у краёв контейнера',
        difficulty: 'Средне',
      },
      {
        text: 'Чем Grid принципиально отличается от Flexbox?',
        type: 'choice',
        answer: 'Grid работает в двух измерениях (строки и колонки), Flexbox — в одном',
        options: [
          'Grid работает в двух измерениях (строки и колонки), Flexbox — в одном',
          'Grid нельзя использовать с адаптивной вёрсткой',
          'Flexbox работает только для текста',
          'Разницы нет, это синонимы'
        ],
        hint: 'Одномерное расположение vs двумерная сетка',
        difficulty: 'Средне',
      },
      {
        text: 'Какое значение position "прилипает" при скролле, пока не выйдет из области родителя?',
        type: 'choice',
        answer: 'sticky',
        options: ['relative', 'absolute', 'fixed', 'sticky'],
        hint: 'Гибрид relative и fixed',
        difficulty: 'Средне',
      },
      {
        text: 'Относительно чего позиционируется элемент с position: absolute?',
        type: 'choice',
        answer: 'Ближайшего предка с position, отличным от static',
        options: [
          'Всегда относительно окна браузера',
          'Ближайшего предка с position, отличным от static',
          'Родителя с display: flex',
          'Ничего, оно не зависит от предков',
        ],
        hint: 'Обычно ставят position: relative на родителя',
        difficulty: 'Сложно',
      },
      {
        text: 'Для чего используются медиа-запросы (@media)?',
        type: 'choice',
        answer: 'Применять разные стили в зависимости от ширины экрана',
        options: [
          'Применять разные стили в зависимости от ширины экрана',
          'Загружать шрифты с сервера',
          'Анимировать элементы',
          'Подключать внешние CSS-файлы',
        ],
        hint: 'Основа адаптивной вёрстки',
        difficulty: 'Легко',
      },
      {
        text: 'Что означает свойство gap: 16px в Flexbox/Grid-контейнере?',
        type: 'choice',
        answer: 'Расстояние между дочерними элементами',
        options: [
          'Расстояние между дочерними элементами',
          'Внутренний отступ контейнера',
          'Высота контейнера',
          'Толщина границы контейнера',
        ],
        hint: 'Раньше для этого использовали margin на каждом элементе',
        difficulty: 'Легко',
      },
    ],
  }
}
