export default function July9WebSocketTasks() {
  return {
    tasks: [
      {
        text: 'Почему обычный HTTP плохо подходит для real-time приложений?',
        type: 'choice',
        answer: 'Сервер не может сам инициировать отправку данных — только отвечает на запросы клиента',
        options: [
          'HTTP слишком быстрый',
          'Сервер не может сам инициировать отправку данных — только отвечает на запросы клиента',
          'HTTP не умеет передавать текст',
          'HTTP работает только в Chrome',
        ],
        hint: 'Модель «запрос → ответ», инициатор всегда клиент',
        difficulty: 'Средне',
      },
      {
        text: 'Что такое polling как способ имитировать real-time?',
        type: 'choice',
        answer: 'Клиент периодически спрашивает сервер, есть ли что-то новое',
        options: [
          'Сервер сам присылает данные мгновенно',
          'Клиент периодически спрашивает сервер, есть ли что-то новое',
          'Соединение никогда не закрывается',
          'Данные шифруются дважды',
        ],
        hint: 'Большинство таких запросов возвращают «нет»',
        difficulty: 'Средне',
      },
      {
        text: 'Что такое WebSocket?',
        type: 'choice',
        answer: 'Протокол постоянного двунаправленного соединения между клиентом и сервером',
        options: [
          'Тип базы данных',
          'Протокол постоянного двунаправленного соединения между клиентом и сервером',
          'Формат картинок',
          'Библиотека для стилей CSS',
        ],
        hint: 'Обе стороны могут слать сообщения в любой момент',
        difficulty: 'Легко',
      },
      {
        text: 'Какую схему адреса использует WebSocket?',
        type: 'choice',
        answer: 'ws:// (или wss:// для защищённого)',
        options: ['http://', 'ws:// (или wss:// для защищённого)', 'ftp://', 'db://'],
        hint: 'wss — это WebSocket поверх TLS',
        difficulty: 'Легко',
      },
      {
        text: 'Каким HTTP-кодом сервер подтверждает переход на WebSocket?',
        type: 'choice',
        answer: '101 Switching Protocols',
        options: ['200 OK', '101 Switching Protocols', '404 Not Found', '301 Moved Permanently'],
        hint: 'Соединение начинается как HTTP с заголовком Upgrade',
        difficulty: 'Сложно',
      },
      {
        text: 'Что означает «двунаправленное» (full-duplex) соединение WebSocket?',
        type: 'choice',
        answer: 'И клиент, и сервер могут отправлять данные независимо в любой момент',
        options: [
          'Данные идут только от сервера к клиенту',
          'И клиент, и сервер могут отправлять данные независимо в любой момент',
          'Соединение работает только по будням',
          'Можно подключить ровно два устройства',
        ],
        hint: 'В отличие от HTTP, где инициатор только клиент',
        difficulty: 'Средне',
      },
      {
        text: 'Какое событие объекта WebSocket в браузере срабатывает при получении данных от сервера?',
        type: 'choice',
        answer: 'onmessage (данные в event.data)',
        options: ['onopen', 'onmessage (данные в event.data)', 'onclose', 'onerror'],
        hint: 'onopen — при установке, onclose — при закрытии',
        difficulty: 'Средне',
      },
      {
        text: 'Какой метод объекта WebSocket отправляет данные серверу?',
        type: 'choice',
        answer: 'socket.send(...)',
        options: ['socket.post(...)', 'socket.send(...)', 'socket.emit(...)', 'socket.write(...)'],
        hint: 'Обычно шлют JSON через JSON.stringify',
        difficulty: 'Легко',
      },
      {
        text: 'Что обычно используют для WebSocket на стороне Django?',
        type: 'choice',
        answer: 'Django Channels (consumer-классы)',
        options: [
          'Обычные Django views',
          'Django Channels (consumer-классы)',
          'Django Admin',
          'Django Templates',
        ],
        hint: 'Обычный Django заточен под модель запрос-ответ',
        difficulty: 'Средне',
      },
      {
        text: 'Что такое broadcast в контексте WebSocket-чата?',
        type: 'choice',
        answer: 'Рассылка сообщения всем участникам комнаты, а не только отправителю',
        options: [
          'Шифрование сообщения',
          'Рассылка сообщения всем участникам комнаты, а не только отправителю',
          'Удаление сообщения',
          'Проверка пароля',
        ],
        hint: 'Соединения группируют в «комнаты» (channel groups)',
        difficulty: 'Средне',
      },
    ],
  }
}
