export default function July1HtmlTasks() {
  return {
    tasks: [
      {
        text: 'Какой тег задаёт главный заголовок страницы (должен быть один)?',
        type: 'choice',
        answer: '<h1>',
        options: ['<head>', '<h1>', '<title>', '<header>'],
        hint: 'Заголовки от h1 до h6, главный — первый',
        difficulty: 'Легко',
      },
      {
        text: 'Какой атрибут изображения обязателен для доступности и валидности?',
        type: 'choice',
        answer: 'alt',
        options: ['title', 'src', 'name', 'alt'],
        hint: 'Текстовое описание картинки для скринридеров',
        difficulty: 'Легко',
      },
      {
        text: 'Какой тег создаёт нумерованный список?',
        type: 'choice',
        answer: '<ol>',
        options: ['<ul>', '<li>', '<ol>', '<dl>'],
        hint: 'ol — ordered list, ul — unordered (маркированный)',
        difficulty: 'Легко',
      },
      {
        text: 'Что из перечисленного — семантический тег?',
        type: 'choice',
        answer: '<nav>',
        options: ['<nav>', '<div>', '<span>', '<b>'],
        hint: 'Семантика описывает смысл: навигация',
        difficulty: 'Средне',
      },
      {
        text: 'Какой тег обозначает ячейку-заголовок в таблице?',
        type: 'choice',
        answer: '<th>',
        options: ['<td>', '<tr>', '<thead>', '<th>'],
        hint: 'th — table header, td — обычная ячейка',
        difficulty: 'Средне',
      },
      {
        text: 'Какой атрибут связывает <label> с полем ввода?',
        type: 'choice',
        answer: 'for (совпадает с id поля)',
        options: ['name', 'for (совпадает с id поля)', 'class', 'href'],
        hint: 'for у label = id у input',
        difficulty: 'Средне',
      },
      {
        text: 'Какой тип input проверяет формат электронной почты?',
        type: 'choice',
        answer: 'type="email"',
        options: ['type="text"', 'type="mail"', 'type="email"', 'type="address"'],
        hint: 'Специальный тип с встроенной валидацией',
        difficulty: 'Легко',
      },
      {
        text: 'Какая вложенность тегов валидна?',
        type: 'choice',
        answer: '<p><strong>текст</strong></p>',
        options: [
          '<p><strong>текст</strong></p>',
          '<p><strong>текст</p></strong>',
          '<strong><p>текст</strong></p>',
          '<p><strong>текст<p></strong>',
        ],
        hint: 'Теги закрываются в обратном порядке, без пересечений',
        difficulty: 'Средне',
      },
      {
        text: 'Какой тег НЕ требует закрывающего (одиночный / self-closing)?',
        type: 'choice',
        answer: '<img>',
        options: ['<p>', '<div>', '<a>', '<img>'],
        hint: 'Картинка не имеет содержимого внутри',
        difficulty: 'Средне',
      },
      {
        text: 'Что делает <meta charset="UTF-8">?',
        type: 'choice',
        answer: 'Задаёт кодировку страницы (корректная кириллица)',
        options: [
          'Подключает файл стилей',
          'Задаёт кодировку страницы (корректная кириллица)',
          'Задаёт заголовок вкладки',
          'Создаёт форму',
        ],
        hint: 'Без неё кириллица может отображаться «кракозябрами»',
        difficulty: 'Легко',
      },
    ],
  }
}
