export default function July5DjangoTasks() {
  return {
    tasks: [
      {
        text: 'Что означает аббревиатура CRUD?',
        type: 'choice',
        answer: 'Create, Read, Update, Delete — четыре базовые операции над данными',
        options: [
          'Create, Run, Update, Deploy',
          'Create, Read, Update, Delete — четыре базовые операции над данными',
          'Copy, Render, Undo, Download',
          'Connect, Read, Use, Disconnect',
        ],
        hint: 'Создать, прочитать, обновить, удалить',
        difficulty: 'Легко',
      },
      {
        text: 'Какой HTTP-метод используется для создания новой записи в REST API?',
        type: 'choice',
        answer: 'POST',
        options: ['GET', 'POST', 'DELETE', 'PATCH'],
        hint: 'GET — читать, DELETE — удалять',
        difficulty: 'Легко',
      },
      {
        text: 'Что вернёт запрос GET /api/books/5/ в правильно спроектированном REST API?',
        type: 'choice',
        answer: 'Одну книгу с id=5',
        options: [
          'Список всех книг',
          'Одну книгу с id=5',
          'Удалит книгу с id=5',
          'Создаст 5 новых книг',
        ],
        hint: 'GET на URL с id — чтение одного ресурса',
        difficulty: 'Средне',
      },
      {
        text: 'Что такое модель (Model) в Django?',
        type: 'choice',
        answer: 'Python-класс, который Django превращает в таблицу базы данных',
        options: [
          'HTML-шаблон страницы',
          'Python-класс, который Django превращает в таблицу базы данных',
          'Файл со стилями CSS',
          'Функция для маршрутизации URL',
        ],
        hint: 'Каждое поле класса — колонка таблицы',
        difficulty: 'Средне',
      },
      {
        text: 'Зачем нужен сериализатор (Serializer) в Django REST Framework?',
        type: 'choice',
        answer: 'Превращает объект модели в JSON и обратно, проверяя входящие данные',
        options: [
          'Запускает сервер',
          'Превращает объект модели в JSON и обратно, проверяя входящие данные',
          'Создаёт HTML-страницы',
          'Управляет паролями пользователей',
        ],
        hint: 'Мост между Python-объектом и JSON',
        difficulty: 'Средне',
      },
      {
        text: 'Что даёт использование ModelViewSet в DRF?',
        type: 'choice',
        answer: 'Автоматически генерирует все CRUD-эндпоинты по queryset и сериализатору',
        options: [
          'Только удаляет записи',
          'Автоматически генерирует все CRUD-эндпоинты по queryset и сериализатору',
          'Рисует графики данных',
          'Отправляет email пользователям',
        ],
        hint: 'Один класс = список, деталь, создание, обновление, удаление',
        difficulty: 'Сложно',
      },
      {
        text: 'Какие две команды применяют изменения модели к базе данных?',
        type: 'choice',
        answer: 'makemigrations и migrate',
        options: [
          'makemigrations и migrate',
          'runserver и startapp',
          'install и build',
          'commit и push',
        ],
        hint: 'Сначала создать файл миграции, потом применить его',
        difficulty: 'Средне',
      },
      {
        text: 'Какой статус-код обычно возвращает сервер при успешном создании записи (POST)?',
        type: 'choice',
        answer: '201 Created',
        options: ['200 OK', '201 Created', '404 Not Found', '500 Internal Server Error'],
        hint: 'Отдельный код именно для «создано»',
        difficulty: 'Средне',
      },
      {
        text: 'Что делает Router (роутер) в Django REST Framework?',
        type: 'choice',
        answer: 'Автоматически создаёт набор URL-адресов для ViewSet',
        options: [
          'Подключается к Wi-Fi',
          'Автоматически создаёт набор URL-адресов для ViewSet',
          'Хранит пароли',
          'Компилирует Python в машинный код',
        ],
        hint: 'register(r"books", ...) → все URL ресурса',
        difficulty: 'Средне',
      },
      {
        text: 'Какой статус-код означает, что записи с запрошенным id не существует?',
        type: 'choice',
        answer: '404 Not Found',
        options: ['200 OK', '204 No Content', '404 Not Found', '400 Bad Request'],
        hint: '«Не найдено»',
        difficulty: 'Легко',
      },
    ],
  }
}
