// Задания SQL-тренажёра. Эталонный запрос живёт только на сервере: ответ
// студента сравнивается с его результатом, сам запрос наружу не отдаётся.
// Порядок строк не важен (в заданиях нет ORDER BY), столбцы — как в условии.

const TASKS = [
  {
    id: 1,
    title: 'Весь каталог разделов',
    text: 'Выведи все столбцы и все строки таблицы `categories`.',
    hint: 'Звёздочка `*` после SELECT означает «все столбцы».',
    sql: 'SELECT * FROM categories',
  },
  {
    id: 2,
    title: 'Контакты покупателей',
    text: 'Выведи `id`, `email` и `city` всех покупателей из таблицы `customers`.',
    hint: 'Нужные столбцы перечисляются через запятую после SELECT.',
    sql: 'SELECT id, email, city FROM customers',
  },
  {
    id: 3,
    title: 'Товары до 1000 ₽',
    text: 'Найди товары дешевле 1000 рублей: выведи их название (`name`) и цену (`price`).',
    hint: 'Условие отбора пишется в WHERE, «дешевле» — это знак `<`.',
    sql: 'SELECT name, price FROM products WHERE price < 1000',
  },
  {
    id: 4,
    title: 'Крупные отмены',
    text: 'Выведи `id`, `customer_id` и `total_amount` отменённых заказов (статус `cancelled`) на сумму больше 50 000 рублей.',
    hint: 'Два условия должны выполняться одновременно — соедини их через AND. Текст в SQL пишется в одинарных кавычках.',
    sql: "SELECT id, customer_id, total_amount FROM orders WHERE status = 'cancelled' AND total_amount > 50000",
  },
  {
    id: 5,
    title: 'Две столицы',
    text: 'Выведи `id`, `first_name` и `city` покупателей из Москвы или Санкт-Петербурга.',
    hint: 'Подойдёт OR или IN (...). Города записаны полностью: `Москва`, `Санкт-Петербург`.',
    sql: "SELECT id, first_name, city FROM customers WHERE city = 'Москва' OR city = 'Санкт-Петербург'",
  },
  {
    id: 6,
    title: 'Без телефона',
    text: 'Выведи `id` и `email` покупателей, у которых не указан телефон (`phone`).',
    hint: 'Пустое значение в базе — это NULL. Сравнение `= NULL` никогда не срабатывает, нужен оператор IS NULL.',
    sql: 'SELECT id, email FROM customers WHERE phone IS NULL',
  },
  {
    id: 7,
    title: 'Сколько доставлено',
    text: 'Посчитай, сколько заказов доставлено (статус `delivered`). В ответе — одно число.',
    hint: 'Количество строк считает агрегатная функция COUNT(*).',
    sql: "SELECT COUNT(*) FROM orders WHERE status = 'delivered'",
  },
  {
    id: 8,
    title: 'Выручка через СБП',
    text: 'Посчитай общую сумму (`total_amount`) доставленных заказов (`delivered`), оплаченных через СБП (`payment_method` = `sbp`). В ответе — одно число.',
    hint: 'Сумму значений столбца считает SUM(...). Условий два — соедини их через AND.',
    sql: "SELECT SUM(total_amount) FROM orders WHERE status = 'delivered' AND payment_method = 'sbp'",
  },
  {
    id: 9,
    title: 'Средняя цена Samsung',
    text: 'Найди среднюю цену (`price`) товаров бренда `Samsung`. В ответе — одно число.',
    hint: 'Среднее считает AVG(...). Округлять не обязательно — проверка допускает точность до копеек.',
    sql: "SELECT AVG(price) FROM products WHERE brand = 'Samsung'",
  },
  {
    id: 10,
    title: 'Ценовой диапазон',
    text: 'Выведи минимальную и максимальную цену среди активных товаров (`is_active` = 1). Два столбца: сначала минимум, потом максимум.',
    hint: 'Нужны MIN(...) и MAX(...) в одном SELECT.',
    sql: 'SELECT MIN(price), MAX(price) FROM products WHERE is_active = 1',
  },
]

// Описание столбцов для подсказки в интерфейсе
const COLUMN_DOCS = {
  categories: {
    _: 'Разделы каталога: верхний уровень и подкатегории',
    id: 'идентификатор раздела',
    parent_id: 'родительский раздел; NULL у разделов верхнего уровня',
    name: 'название',
    slug: 'адрес раздела в URL',
    is_active: '1 — раздел показывается в каталоге, 0 — скрыт',
    sort_order: 'порядок вывода',
    created_at: 'дата создания (UTC)',
  },
  customers: {
    _: 'Покупатели маркетплейса',
    id: 'идентификатор покупателя',
    email: 'электронная почта',
    phone: 'телефон в том виде, как его ввели; бывает NULL',
    first_name: 'имя',
    last_name: 'фамилия; бывает NULL',
    gender: "пол: 'm', 'f' или NULL",
    birth_date: 'дата рождения (ГГГГ-ММ-ДД); бывает NULL',
    city: 'город; бывает NULL',
    registered_at: 'дата регистрации (UTC)',
    last_login_at: 'последний вход; NULL — ни разу не заходил после регистрации',
    is_verified: '1 — почта подтверждена',
    loyalty_points: 'баллы программы лояльности',
    marketing_consent: '1 — согласен на рассылки',
    deleted_at: 'когда удалил аккаунт; NULL — аккаунт активен',
  },
  products: {
    _: 'Товары каталога',
    id: 'идентификатор товара',
    sku: 'артикул',
    name: 'название',
    brand: 'бренд; бывает NULL',
    category_id: 'раздел → categories.id',
    price: 'цена, ₽',
    old_price: 'цена до скидки; NULL — скидки нет',
    stock: 'остаток на складе, шт.',
    rating: 'средняя оценка; NULL — отзывов нет',
    reviews_count: 'количество отзывов',
    weight_grams: 'вес, г; бывает NULL',
    is_active: '1 — товар продаётся, 0 — снят с продажи',
    created_at: 'дата добавления (UTC)',
    updated_at: 'дата последнего изменения; бывает NULL',
  },
  orders: {
    _: 'Заказы',
    id: 'номер заказа',
    customer_id: 'покупатель → customers.id',
    status: "статус: 'new', 'processing', 'paid', 'shipped', 'delivered', 'cancelled', 'returned'",
    payment_method: "оплата: 'card', 'sbp', 'cash', 'installments' или NULL",
    promo_code: 'промокод; NULL — без промокода',
    delivery_type: "доставка: 'pickup_point', 'courier', 'post'",
    delivery_city: 'город доставки; бывает NULL',
    items_count: 'товаров в заказе, шт.',
    subtotal: 'сумма товаров, ₽',
    discount_amount: 'скидка, ₽',
    delivery_price: 'стоимость доставки, ₽',
    total_amount: 'итого к оплате, ₽',
    comment: 'комментарий покупателя; бывает NULL',
    created_at: 'когда оформлен (UTC)',
    paid_at: 'когда оплачен; NULL — не оплачен онлайн',
    delivered_at: 'когда доставлен; NULL — ещё не доставлен',
  },
  order_items: {
    _: 'Позиции заказов: какие товары и сколько',
    id: 'идентификатор позиции',
    order_id: 'заказ → orders.id',
    product_id: 'товар → products.id',
    quantity: 'количество, шт.',
    unit_price: 'цена за штуку на момент заказа, ₽',
  },
}

module.exports = { TASKS, COLUMN_DOCS }
