// Задания SQL-тренажёра. Эталонный запрос живёт только на сервере: ответ
// студента сравнивается с его результатом, сам запрос наружу не отдаётся.
// Порядок строк не важен (в заданиях нет ORDER BY), столбцы — как в условии.

// Темы и задачи. В задачах с ordered: true важен и порядок строк — там в
// условии всегда сказано, как упорядочивать равные значения, иначе ответ
// неоднозначен.
const CATEGORIES = [
  {
    id: 'select',
    title: 'SELECT и FROM: первый запрос',
    tasks: [
      { title: 'Весь каталог разделов', text: 'Выведи все столбцы и все строки таблицы `categories`.', hint: 'Звёздочка `*` после SELECT означает «все столбцы».', sql: 'SELECT * FROM categories' },
      { title: 'Контакты покупателей', text: 'Выведи `id`, `email` и `city` всех покупателей из таблицы `customers`.', hint: 'Нужные столбцы перечисляются через запятую после SELECT.', sql: 'SELECT id, email, city FROM customers' },
      { title: 'Витрина товаров', text: 'Выведи название (`name`) и цену (`price`) всех товаров.', hint: 'SELECT name, price FROM …', sql: 'SELECT name, price FROM products' },
      { title: 'Складские остатки', text: 'Выведи артикул (`sku`) и остаток на складе (`stock`) всех товаров.', hint: 'Артикулы и остатки лежат в таблице `products`.', sql: 'SELECT sku, stock FROM products' },
      { title: 'Все позиции заказов', text: 'Выведи все столбцы таблицы `order_items`.', hint: 'Таблица большая — 30 тысяч строк. На экране покажутся первые 200, а проверяется весь результат.', sql: 'SELECT * FROM order_items' },
      { title: 'Список заказов', text: 'Выведи `id`, `status` и `total_amount` всех заказов.', hint: 'Таблица заказов — `orders`.', sql: 'SELECT id, status, total_amount FROM orders' },
      { title: 'Псевдонимы', text: 'Выведи название товара под именем `title` и его цену под именем `cost`.', hint: 'Псевдоним задаётся через AS: `name AS title`.', sql: 'SELECT name AS title, price AS cost FROM products' },
      { title: 'Сумма без доставки', text: 'Выведи `id` каждого заказа и сумму заказа без доставки: `total_amount` минус `delivery_price`.', hint: 'В SELECT можно считать: `total_amount - delivery_price`.', sql: 'SELECT id, total_amount - delivery_price FROM orders' },
      { title: 'Какие бывают статусы', text: 'Выведи список всех различных статусов заказов — каждый статус один раз.', hint: 'Повторы убирает DISTINCT: `SELECT DISTINCT …`.', sql: 'SELECT DISTINCT status FROM orders' },
      { title: 'Доставка и оплата', text: 'Выведи все различные сочетания способа доставки (`delivery_type`) и способа оплаты (`payment_method`).', hint: 'DISTINCT действует на всю строку целиком, то есть на пару столбцов.', sql: 'SELECT DISTINCT delivery_type, payment_method FROM orders' },
    ],
  },
  {
    id: 'where',
    title: 'WHERE: фильтрация строк',
    tasks: [
      { title: 'Товары до 1000 ₽', text: 'Найди товары дешевле 1000 рублей: выведи их название (`name`) и цену (`price`).', hint: 'Условие отбора пишется в WHERE, «дешевле» — это знак `<`.', sql: 'SELECT name, price FROM products WHERE price < 1000' },
      { title: 'Крупные отмены', text: 'Выведи `id`, `customer_id` и `total_amount` отменённых заказов (статус `cancelled`) на сумму больше 50 000 рублей.', hint: 'Два условия должны выполняться одновременно — соедини их через AND. Текст в SQL пишется в одинарных кавычках.', sql: "SELECT id, customer_id, total_amount FROM orders WHERE status = 'cancelled' AND total_amount > 50000" },
      { title: 'Две столицы', text: 'Выведи `id`, `first_name` и `city` покупателей из Москвы или Санкт-Петербурга.', hint: 'Подойдёт OR или IN (...). Города записаны полностью: `Москва`, `Санкт-Петербург`.', sql: "SELECT id, first_name, city FROM customers WHERE city = 'Москва' OR city = 'Санкт-Петербург'" },
      { title: 'Только Apple', text: 'Выведи `id`, `name` и `price` товаров бренда `Apple`.', hint: 'Сравнение строк чувствительно к регистру: `Apple` и `apple` — разные значения.', sql: "SELECT id, name, price FROM products WHERE brand = 'Apple'" },
      { title: 'Заказы сентября', text: 'Выведи `id` и `created_at` заказов, оформленных в сентябре 2026 года.', hint: 'Даты хранятся текстом вида `2026-09-15 12:30:00`, их можно сравнивать как строки: `>= \'2026-09-01\'` и `< \'2026-10-01\'`.', sql: "SELECT id, created_at FROM orders WHERE created_at >= '2026-09-01' AND created_at < '2026-10-01'" },
      { title: 'Средний ценовой сегмент', text: 'Выведи `name` и `price` товаров с ценой от 5 000 до 10 000 рублей включительно.', hint: 'BETWEEN 5000 AND 10000 включает обе границы.', sql: 'SELECT name, price FROM products WHERE price BETWEEN 5000 AND 10000' },
      { title: 'Отмены и возвраты', text: 'Выведи `id` и `status` заказов, которые отменены (`cancelled`) или возвращены (`returned`).', hint: 'Список значений удобно проверять через IN (...).', sql: "SELECT id, status FROM orders WHERE status IN ('cancelled', 'returned')" },
      { title: 'Линейка Pro', text: 'Выведи `id` и `name` товаров, в названии которых встречается `Pro`.', hint: 'LIKE с шаблоном: `%` — любое количество любых символов.', sql: "SELECT id, name FROM products WHERE name LIKE '%Pro%'" },
      { title: 'Снято с продажи', text: 'Выведи `id` и `name` товаров, которые сейчас не продаются (`is_active` = 0).', hint: 'Флаги хранятся числами 0 и 1.', sql: 'SELECT id, name FROM products WHERE is_active = 0' },
      { title: 'Курьером и онлайн', text: 'Выведи `id` и `payment_method` заказов с доставкой курьером (`courier`), оплаченных картой (`card`) или через СБП (`sbp`).', hint: 'AND выполняется раньше OR — поставь скобки вокруг условия про оплату.', sql: "SELECT id, payment_method FROM orders WHERE delivery_type = 'courier' AND (payment_method = 'card' OR payment_method = 'sbp')" },
    ],
  },
  {
    id: 'order',
    title: 'ORDER BY и LIMIT: сортировка и порции',
    tasks: [
      { ordered: true, title: 'От дешёвых к дорогим', text: 'Выведи `name` и `price` всех товаров по возрастанию цены; при равной цене — по возрастанию `id`.', hint: 'Сортировок может быть несколько: `ORDER BY price, id`.', sql: 'SELECT name, price FROM products ORDER BY price, id' },
      { ordered: true, title: 'Десять самых дорогих', text: 'Выведи `id`, `name` и `price` десяти самых дорогих товаров — от дорогих к дешёвым; при равной цене — по возрастанию `id`.', hint: 'DESC — по убыванию. LIMIT 10 оставит первые десять строк.', sql: 'SELECT id, name, price FROM products ORDER BY price DESC, id LIMIT 10' },
      { ordered: true, title: 'Свежие заказы', text: 'Выведи `id` и `created_at` пяти самых новых заказов — сначала самый новый; при одинаковом времени — по убыванию `id`.', hint: 'Новые — значит с наибольшей датой: `ORDER BY created_at DESC`.', sql: 'SELECT id, created_at FROM orders ORDER BY created_at DESC, id DESC LIMIT 5' },
      { ordered: true, title: 'Алфавитный список', text: 'Выведи `id`, `last_name` и `first_name` всех покупателей по алфавиту: по фамилии, затем по имени, затем по `id`.', hint: 'Фамилия бывает NULL — при сортировке по возрастанию такие строки окажутся первыми.', sql: 'SELECT id, last_name, first_name FROM customers ORDER BY last_name, first_name, id' },
      { ordered: true, title: 'Лучшие по рейтингу', text: 'Выведи `id`, `name`, `rating` и `reviews_count` десяти товаров с самым высоким рейтингом. При равном рейтинге выше тот, у кого больше отзывов, дальше — по возрастанию `id`.', hint: 'NULL при сортировке по убыванию уходит в конец — товары без отзывов в топ не попадут.', sql: 'SELECT id, name, rating, reviews_count FROM products ORDER BY rating DESC, reviews_count DESC, id LIMIT 10' },
      { ordered: true, title: 'Третья страница каталога', text: 'Каталог показывает по 20 товаров на странице, отсортированных по `id`. Выведи `id` и `name` товаров третьей страницы.', hint: 'Пропустить первые 40 строк помогает OFFSET: `LIMIT 20 OFFSET 40`.', sql: 'SELECT id, name FROM products ORDER BY id LIMIT 20 OFFSET 40' },
      { ordered: true, title: 'Крупнейшие доставки', text: 'Выведи `id` и `total_amount` пяти самых крупных доставленных заказов (`delivered`) — от большего к меньшему; при равной сумме — по возрастанию `id`.', hint: 'WHERE отбирает строки до сортировки, LIMIT срабатывает в самом конце.', sql: "SELECT id, total_amount FROM orders WHERE status = 'delivered' ORDER BY total_amount DESC, id LIMIT 5" },
      { ordered: true, title: 'Первые в Казани', text: 'Выведи `id`, `first_name` и `registered_at` десяти покупателей из Казани, которые зарегистрировались раньше всех; при одинаковой дате — по `id`.', hint: 'Раньше всех — по возрастанию даты регистрации.', sql: "SELECT id, first_name, registered_at FROM customers WHERE city = 'Казань' ORDER BY registered_at, id LIMIT 10" },
      { ordered: true, title: 'Самые тяжёлые', text: 'Выведи `id`, `name` и `weight_grams` трёх самых тяжёлых товаров — от тяжёлого к лёгкому; при равном весе — по `id`.', hint: 'Вес не указан у части товаров (NULL) — при убывании они окажутся в конце.', sql: 'SELECT id, name, weight_grams FROM products ORDER BY weight_grams DESC, id LIMIT 3' },
      { ordered: true, title: 'Самые большие скидки', text: 'Выведи `id`, `name` и размер скидки в рублях (`old_price` минус `price`) для десяти товаров с самой большой скидкой; при равной скидке — по `id`. Товары без старой цены не учитывай.', hint: 'Сортировать можно по выражению или по псевдониму столбца.', sql: 'SELECT id, name, old_price - price AS discount FROM products WHERE old_price IS NOT NULL ORDER BY discount DESC, id LIMIT 10' },
    ],
  },
  {
    id: 'aggregate',
    title: 'Агрегаты и GROUP BY',
    tasks: [
      { title: 'Сколько доставлено', text: 'Посчитай, сколько заказов доставлено (статус `delivered`). В ответе — одно число.', hint: 'Количество строк считает агрегатная функция COUNT(*).', sql: "SELECT COUNT(*) FROM orders WHERE status = 'delivered'" },
      { title: 'Выручка через СБП', text: 'Посчитай общую сумму (`total_amount`) доставленных заказов (`delivered`), оплаченных через СБП (`payment_method` = `sbp`). В ответе — одно число.', hint: 'Сумму значений столбца считает SUM(...). Условий два — соедини их через AND.', sql: "SELECT SUM(total_amount) FROM orders WHERE status = 'delivered' AND payment_method = 'sbp'" },
      { title: 'Средняя цена Samsung', text: 'Найди среднюю цену (`price`) товаров бренда `Samsung`. В ответе — одно число.', hint: 'Среднее считает AVG(...). Округлять не обязательно — проверка допускает точность до копеек.', sql: "SELECT AVG(price) FROM products WHERE brand = 'Samsung'" },
      { title: 'Ценовой диапазон', text: 'Выведи минимальную и максимальную цену среди активных товаров (`is_active` = 1). Два столбца: сначала минимум, потом максимум.', hint: 'Нужны MIN(...) и MAX(...) в одном SELECT.', sql: 'SELECT MIN(price), MAX(price) FROM products WHERE is_active = 1' },
      { title: 'Размер аудитории', text: 'Посчитай, сколько всего покупателей в базе.', hint: 'COUNT(*) считает все строки.', sql: 'SELECT COUNT(*) FROM customers' },
      { title: 'Оставили телефон', text: 'Посчитай, у скольких покупателей указан телефон.', hint: 'COUNT(столбец) пропускает NULL, в отличие от COUNT(*).', sql: 'SELECT COUNT(phone) FROM customers' },
      { title: 'География', text: 'Посчитай, из скольких разных городов покупатели (пустой город не считается).', hint: 'COUNT(DISTINCT city) — количество различных значений без NULL.', sql: 'SELECT COUNT(DISTINCT city) FROM customers' },
      { title: 'Заказы по статусам', text: 'Для каждого статуса выведи сам статус и количество заказов с ним.', hint: 'GROUP BY status разбивает заказы на группы, COUNT(*) считает строки в каждой.', sql: 'SELECT status, COUNT(*) FROM orders GROUP BY status' },
      { title: 'Средний чек по оплате', text: 'Для каждого способа оплаты (`payment_method`) выведи способ и средний чек (`total_amount`). Заказы без способа оплаты — тоже отдельная группа.', hint: 'NULL при группировке собирается в одну общую группу.', sql: 'SELECT payment_method, AVG(total_amount) FROM orders GROUP BY payment_method' },
      { title: 'Разделы каталога', text: 'Для каждой категории товаров (`category_id`) выведи её `category_id`, количество товаров и максимальную цену.', hint: 'В одном SELECT можно считать несколько агрегатов сразу.', sql: 'SELECT category_id, COUNT(*), MAX(price) FROM products GROUP BY category_id' },
    ],
  },
  {
    id: 'having',
    title: 'HAVING и порядок выполнения запроса',
    tasks: [
      { title: 'Крупные бренды', text: 'Выведи бренды, у которых больше 40 товаров: `brand` и количество товаров. Товары без бренда не учитывай.', hint: 'WHERE фильтрует строки до группировки, HAVING — готовые группы после неё.', sql: 'SELECT brand, COUNT(*) FROM products WHERE brand IS NOT NULL GROUP BY brand HAVING COUNT(*) > 40' },
      { title: 'Города-миллионники выручки', text: 'Выведи города доставки (`delivery_city`), где выручка доставленных заказов (`delivered`) больше 25 000 000 рублей: город и выручку.', hint: 'Сначала WHERE по статусу, потом GROUP BY по городу, потом HAVING по сумме.', sql: "SELECT delivery_city, SUM(total_amount) FROM orders WHERE status = 'delivered' GROUP BY delivery_city HAVING SUM(total_amount) > 25000000" },
      { title: 'Постоянные покупатели', text: 'Выведи `customer_id` и количество заказов для покупателей, сделавших больше 20 заказов.', hint: 'Группируй по `customer_id` и фильтруй группы через HAVING COUNT(*) > 20.', sql: 'SELECT customer_id, COUNT(*) FROM orders GROUP BY customer_id HAVING COUNT(*) > 20' },
      { title: 'Дорогие категории', text: 'Выведи `category_id` и среднюю цену товаров для категорий, где средняя цена выше 50 000 рублей.', hint: 'AVG в HAVING считается по группе.', sql: 'SELECT category_id, AVG(price) FROM products GROUP BY category_id HAVING AVG(price) > 50000' },
      { title: 'Бренды с высоким рейтингом', text: 'Среди активных товаров (`is_active` = 1) найди бренды со средним рейтингом выше 4,3: выведи `brand` и средний рейтинг.', hint: 'AVG пропускает NULL — товары без оценок на среднее не влияют.', sql: 'SELECT brand, AVG(rating) FROM products WHERE is_active = 1 GROUP BY brand HAVING AVG(rating) > 4.3' },
      { title: 'Популярные способы оплаты', text: 'Выведи способы оплаты, которыми оплачено больше 2000 заказов: `payment_method` и количество заказов.', hint: 'Группа NULL тоже участвует в HAVING, но здесь она до порога не дотянет.', sql: 'SELECT payment_method, COUNT(*) FROM orders GROUP BY payment_method HAVING COUNT(*) > 2000' },
      { title: 'Ходовые промокоды', text: 'Выведи промокоды, по которым оформили больше 340 заказов: `promo_code` и количество заказов. Заказы без промокода не учитывай.', hint: 'Пустые промокоды убираются ещё в WHERE.', sql: 'SELECT promo_code, COUNT(*) FROM orders WHERE promo_code IS NOT NULL GROUP BY promo_code HAVING COUNT(*) > 340' },
      { title: 'Псевдоним в HAVING', text: 'Выведи статусы заказов, у которых средняя сумма больше 59 000 рублей: `status` и среднюю сумму под именем `avg_total`. В HAVING используй псевдоним `avg_total`.', hint: 'Порядок выполнения: FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT. SQLite разрешает псевдоним в HAVING, но многие базы — нет.', sql: 'SELECT status, AVG(total_amount) AS avg_total FROM orders GROUP BY status HAVING avg_total > 59000' },
      { ordered: true, title: 'Тройка лидеров', text: 'Среди брендов, у которых больше 20 товаров, выведи три с наибольшим числом товаров: `brand` и количество, от большего к меньшему; при равенстве — по названию бренда. Товары без бренда не учитывай.', hint: 'WHERE → GROUP BY → HAVING → ORDER BY → LIMIT — ровно в таком порядке их выполняет база.', sql: 'SELECT brand, COUNT(*) FROM products WHERE brand IS NOT NULL GROUP BY brand HAVING COUNT(*) > 20 ORDER BY COUNT(*) DESC, brand LIMIT 3' },
      { title: 'Где больше подтверждённых', text: 'Выведи города, где больше 100 покупателей с подтверждённой почтой (`is_verified` = 1): `city` и количество. Покупателей без города не учитывай.', hint: 'Оба условия на строки — в WHERE, условие на количество — в HAVING.', sql: 'SELECT city, COUNT(*) FROM customers WHERE is_verified = 1 AND city IS NOT NULL GROUP BY city HAVING COUNT(*) > 100' },
    ],
  },
  {
    id: 'join',
    title: 'JOIN: соединение таблиц',
    tasks: [
      { title: 'Кто вернул заказ', text: 'Для возвращённых заказов (`returned`) выведи `id` заказа и `email` покупателя.', hint: '`orders o JOIN customers c ON c.id = o.customer_id`.', sql: "SELECT o.id, c.email FROM orders o JOIN customers c ON c.id = o.customer_id WHERE o.status = 'returned'" },
      { title: 'Apple по разделам', text: 'Для товаров бренда `Apple` выведи название товара и название его категории.', hint: 'Оба столбца называются `name` — обращайся к ним через таблицу: `p.name`, `c.name`.', sql: "SELECT p.name, c.name FROM products p JOIN categories c ON c.id = p.category_id WHERE p.brand = 'Apple'" },
      { title: 'Состав заказа', text: 'Для заказа с `id` = 1024 выведи название каждого товара, количество (`quantity`) и цену за штуку (`unit_price`).', hint: 'Позиции — в `order_items`, названия — в `products`.', sql: 'SELECT p.name, oi.quantity, oi.unit_price FROM order_items oi JOIN products p ON p.id = oi.product_id WHERE oi.order_id = 1024' },
      { title: 'Ни одного заказа', text: 'Выведи `id` и `email` покупателей, которые не сделали ни одного заказа.', hint: 'LEFT JOIN сохраняет покупателя даже без заказов — у таких строк столбцы заказа будут NULL.', sql: 'SELECT c.id, c.email FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.id IS NULL' },
      { title: 'Никогда не покупали', text: 'Выведи `id` и `name` товаров, которые ни разу не попадали в заказы.', hint: 'Тот же приём: LEFT JOIN к `order_items` и проверка на NULL.', sql: 'SELECT p.id, p.name FROM products p LEFT JOIN order_items oi ON oi.product_id = p.id WHERE oi.id IS NULL' },
      { title: 'Заказы жителей Сочи', text: 'Для каждого покупателя из Сочи выведи его `id`, `first_name` и количество заказов — включая тех, у кого заказов нет (у них 0).', hint: 'LEFT JOIN и COUNT(o.id): COUNT по столбцу заказа не считает NULL, и получится 0.', sql: "SELECT c.id, c.first_name, COUNT(o.id) FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE c.city = 'Сочи' GROUP BY c.id" },
      { title: 'Заказ целиком', text: 'Для заказа с `id` = 1005 выведи `email` покупателя, название каждого товара и количество.', hint: 'Понадобятся четыре таблицы: orders, customers, order_items, products.', sql: 'SELECT c.email, p.name, oi.quantity FROM orders o JOIN customers c ON c.id = o.customer_id JOIN order_items oi ON oi.order_id = o.id JOIN products p ON p.id = oi.product_id WHERE o.id = 1005' },
      { title: 'Раздел и подраздел', text: 'Для каждой подкатегории выведи её название и название родительского раздела.', hint: 'Таблица соединяется сама с собой: `categories c JOIN categories parent ON parent.id = c.parent_id`.', sql: 'SELECT c.name, parent.name FROM categories c JOIN categories parent ON parent.id = c.parent_id' },
      { title: 'Выручка по категориям', text: 'Для доставленных заказов (`delivered`) посчитай выручку по каждой категории товаров: название категории и сумму `quantity * unit_price`.', hint: 'order_items → orders (статус), → products (категория) → categories (название), затем GROUP BY.', sql: "SELECT c.name, SUM(oi.quantity * oi.unit_price) FROM order_items oi JOIN orders o ON o.id = oi.order_id JOIN products p ON p.id = oi.product_id JOIN categories c ON c.id = p.category_id WHERE o.status = 'delivered' GROUP BY c.id" },
      { title: 'Доставка в другой город', text: 'Выведи `id` заказа, город покупателя и город доставки для заказов, доставленных не в тот город, где живёт покупатель. Заказы, где хотя бы один город не указан, не учитывай.', hint: 'Сравнение с NULL через `<>` не даёт истину — такие строки отсеются сами.', sql: 'SELECT o.id, c.city, o.delivery_city FROM orders o JOIN customers c ON c.id = o.customer_id WHERE c.city <> o.delivery_city' },
    ],
  },
  {
    id: 'subquery',
    title: 'Подзапросы и CTE',
    tasks: [
      { title: 'Дороже среднего', text: 'Выведи `id`, `name` и `price` товаров, которые дороже средней цены всех товаров.', hint: 'Среднее посчитает подзапрос: `price > (SELECT AVG(price) FROM products)`.', sql: 'SELECT id, name, price FROM products WHERE price > (SELECT AVG(price) FROM products)' },
      { title: 'Были возвраты', text: 'Выведи `id` и `email` покупателей, у которых есть хотя бы один возвращённый заказ (`returned`).', hint: '`id IN (SELECT customer_id FROM orders WHERE …)`.', sql: "SELECT id, email FROM customers WHERE id IN (SELECT customer_id FROM orders WHERE status = 'returned')" },
      { title: 'Пустые разделы', text: 'Выведи `id` и `name` категорий, к которым не привязан ни один товар.', hint: 'NOT IN (SELECT category_id FROM products). В `category_id` нет NULL, поэтому NOT IN здесь безопасен.', sql: 'SELECT id, name FROM categories WHERE id NOT IN (SELECT category_id FROM products)' },
      { title: 'Заказы в строке покупателя', text: 'Для каждого покупателя из Томска выведи `id`, `first_name` и количество его заказов — подзапросом прямо в SELECT.', hint: 'Коррелированный подзапрос: `(SELECT COUNT(*) FROM orders o WHERE o.customer_id = c.id)`.', sql: "SELECT c.id, c.first_name, (SELECT COUNT(*) FROM orders o WHERE o.customer_id = c.id) FROM customers c WHERE c.city = 'Томск'" },
      { title: 'Средний покупатель', text: 'Для каждого покупателя посчитай сумму его доставленных заказов, а затем выведи среднее этих сумм — одно число.', hint: 'Подзапрос во FROM — как временная таблица: `SELECT AVG(spent) FROM (SELECT …) AS t`.', sql: "SELECT AVG(spent) FROM (SELECT customer_id, SUM(total_amount) AS spent FROM orders WHERE status = 'delivered' GROUP BY customer_id)" },
      { title: 'Берут оптом', text: 'Выведи `id` и `name` товаров, которые хотя бы раз заказали в количестве 5 штук и больше.', hint: 'EXISTS проверяет, что подзапрос вернул хоть одну строку.', sql: 'SELECT p.id, p.name FROM products p WHERE EXISTS (SELECT 1 FROM order_items oi WHERE oi.product_id = p.id AND oi.quantity >= 5)' },
      { title: 'Первый CTE', text: 'С помощью WITH выдели доставленные заказы (`delivered`) и посчитай по ним количество заказов в каждом городе доставки: `delivery_city` и количество.', hint: '`WITH delivered AS (SELECT … ) SELECT … FROM delivered GROUP BY …`.', sql: "WITH delivered AS (SELECT * FROM orders WHERE status = 'delivered') SELECT delivery_city, COUNT(*) FROM delivered GROUP BY delivery_city" },
      { title: 'Клуб миллионеров', text: 'Найди покупателей, у которых сумма доставленных заказов больше 1 000 000 рублей: выведи `email` и эту сумму.', hint: 'Сначала CTE с суммами по `customer_id`, затем JOIN с `customers`.', sql: "WITH spent AS (SELECT customer_id, SUM(total_amount) AS total FROM orders WHERE status = 'delivered' GROUP BY customer_id) SELECT c.email, s.total FROM spent s JOIN customers c ON c.id = s.customer_id WHERE s.total > 1000000" },
      { title: 'Флагманы категорий', text: 'Для каждой категории найди самые дорогие товары: выведи `id`, `category_id` и `price` товаров, чья цена равна максимальной цене в их категории.', hint: 'Коррелированный подзапрос: `price = (SELECT MAX(price) FROM products p2 WHERE p2.category_id = p.category_id)`.', sql: 'SELECT id, category_id, price FROM products p WHERE price = (SELECT MAX(price) FROM products p2 WHERE p2.category_id = p.category_id)' },
      { title: 'Доля отмен', text: 'Посчитай, какой процент заказов отменён (`cancelled`), с точностью до двух знаков после запятой — одно число, например 12.34.', hint: 'Два CTE или подзапроса: всего заказов и отменённых. Умножай на 100.0 — иначе деление целых чисел даст 0.', sql: "WITH total AS (SELECT COUNT(*) AS n FROM orders), cancelled AS (SELECT COUNT(*) AS n FROM orders WHERE status = 'cancelled') SELECT ROUND(100.0 * cancelled.n / total.n, 2) FROM total, cancelled" },
    ],
  },
  {
    id: 'window',
    title: 'Оконные функции',
    tasks: [
      { title: 'Нумерация смартфонов', text: 'Пронумеруй смартфоны (`category_id` = 2) от самого дорогого к самому дешёвому: выведи `id`, `price` и номер. При равной цене раньше идёт меньший `id`.', hint: '`ROW_NUMBER() OVER (ORDER BY price DESC, id)`.', sql: 'SELECT id, price, ROW_NUMBER() OVER (ORDER BY price DESC, id) FROM products WHERE category_id = 2' },
      { title: 'Ранг Apple', text: 'Для товаров бренда `Apple` выведи `id`, `price` и ранг по цене: самый дорогой — 1, одинаковые цены получают одинаковый ранг.', hint: 'RANK() после одинаковых значений пропускает номера: 1, 1, 3.', sql: "SELECT id, price, RANK() OVER (ORDER BY price DESC) FROM products WHERE brand = 'Apple'" },
      { title: 'Плотный ранг Samsung', text: 'Для товаров бренда `Samsung` выведи `id`, `price` и ранг по цене без пропусков: самый дорогой — 1.', hint: 'DENSE_RANK() не пропускает номера: 1, 1, 2.', sql: "SELECT id, price, DENSE_RANK() OVER (ORDER BY price DESC) FROM products WHERE brand = 'Samsung'" },
      { title: 'Нарастающий итог', text: 'Для заказов покупателя с `id` = 1 выведи `id` заказа, `created_at`, `total_amount` и нарастающую сумму заказов по времени (при одинаковом времени — по `id`).', hint: '`SUM(total_amount) OVER (ORDER BY created_at, id)`.', sql: 'SELECT id, created_at, total_amount, SUM(total_amount) OVER (ORDER BY created_at, id) FROM orders WHERE customer_id = 1' },
      { title: 'Цена против категории', text: 'Для каждого товара выведи `id`, `category_id`, `price` и среднюю цену товаров его категории.', hint: 'PARTITION BY делит строки на группы, но, в отличие от GROUP BY, не схлопывает их.', sql: 'SELECT id, category_id, price, AVG(price) OVER (PARTITION BY category_id) FROM products' },
      { title: 'Лидер категории', text: 'В каждой категории оставь один самый дорогой товар (при равной цене — с меньшим `id`): выведи `id`, `category_id` и `price`.', hint: 'Пронумеруй товары внутри категории через ROW_NUMBER в CTE, затем оставь строки с номером 1.', sql: 'WITH r AS (SELECT id, category_id, price, ROW_NUMBER() OVER (PARTITION BY category_id ORDER BY price DESC, id) AS rn FROM products) SELECT id, category_id, price FROM r WHERE rn = 1' },
      { title: 'Предыдущий заказ', text: 'Для заказов покупателя с `id` = 2 выведи `id`, `total_amount` и сумму его предыдущего заказа по времени (при одинаковом времени — по `id`). У первого заказа — NULL.', hint: '`LAG(total_amount) OVER (ORDER BY created_at, id)`.', sql: 'SELECT id, total_amount, LAG(total_amount) OVER (ORDER BY created_at, id) FROM orders WHERE customer_id = 2' },
      { title: 'Доля заказа', text: 'Для заказов покупателя с `id` = 3 выведи `id`, `total_amount` и долю заказа в общей сумме его заказов в процентах, округлённую до двух знаков.', hint: 'Пустое окно `OVER ()` — это все строки результата: `SUM(total_amount) OVER ()`.', sql: 'SELECT id, total_amount, ROUND(100.0 * total_amount / SUM(total_amount) OVER (), 2) FROM orders WHERE customer_id = 3' },
      { title: 'Ценовые квартили', text: 'Разбей активные товары (`is_active` = 1) на 4 ценовые группы от дешёвых к дорогим: выведи `id`, `price` и номер группы. При равной цене — по `id`.', hint: '`NTILE(4) OVER (ORDER BY price, id)`.', sql: 'SELECT id, price, NTILE(4) OVER (ORDER BY price, id) FROM products WHERE is_active = 1' },
      { title: 'Топ-3 по выручке', text: 'В каждой категории найди три товара с наибольшей выручкой по всем заказам (`quantity * unit_price`, при равной выручке — меньший `id`): выведи `category_id`, `id` товара и выручку.', hint: 'Первый CTE — выручка по товарам, второй — ROW_NUMBER внутри категории, в конце — номер ≤ 3.', sql: 'WITH rev AS (SELECT p.id, p.category_id, SUM(oi.quantity * oi.unit_price) AS revenue FROM order_items oi JOIN products p ON p.id = oi.product_id GROUP BY p.id), ranked AS (SELECT id, category_id, revenue, ROW_NUMBER() OVER (PARTITION BY category_id ORDER BY revenue DESC, id) AS rn FROM rev) SELECT category_id, id, revenue FROM ranked WHERE rn <= 3' },
    ],
  },
  {
    id: 'nullcase',
    title: 'NULL, CASE',
    tasks: [
      { title: 'Без телефона', text: 'Выведи `id` и `email` покупателей, у которых не указан телефон (`phone`).', hint: 'Пустое значение в базе — это NULL. Сравнение `= NULL` никогда не срабатывает, нужен оператор IS NULL.', sql: 'SELECT id, email FROM customers WHERE phone IS NULL' },
      { title: 'Со скидкой', text: 'Выведи `id`, `name` и `old_price` товаров, у которых указана старая цена.', hint: 'IS NOT NULL.', sql: 'SELECT id, name, old_price FROM products WHERE old_price IS NOT NULL' },
      { title: 'Ловушка неравенства', text: 'Выведи `id` и `brand` всех товаров, кроме бренда `Samsung` — включая товары, у которых бренд не указан.', hint: '`brand <> \'Samsung\'` для NULL даёт не «истину», а «неизвестно» — такие строки теряются. Добавь `OR brand IS NULL`.', sql: "SELECT id, brand FROM products WHERE brand <> 'Samsung' OR brand IS NULL" },
      { title: 'Город по умолчанию', text: 'Выведи `id` каждого покупателя и его город, а если город не указан — текст `Не указан`.', hint: 'COALESCE возвращает первое значение, которое не NULL.', sql: "SELECT id, COALESCE(city, 'Не указан') FROM customers" },
      { title: 'Честный средний рейтинг', text: 'Посчитай средний рейтинг всех товаров, считая товары без оценок за 0. Одно число.', hint: 'AVG(rating) пропустит NULL, а нужно учесть их нулём: AVG(COALESCE(rating, 0)).', sql: 'SELECT AVG(COALESCE(rating, 0)) FROM products' },
      { title: 'Без оценок', text: 'Посчитай, у скольких товаров нет рейтинга. Одно число.', hint: 'COUNT(*) − COUNT(rating) или SUM(rating IS NULL).', sql: 'SELECT COUNT(*) - COUNT(rating) FROM products' },
      { title: 'Ценовая категория', text: 'Для каждого товара выведи `id`, `price` и ценовую категорию: `дёшево` — меньше 1000, `средне` — от 1000 до 9999.99, `дорого` — от 10 000 и выше.', hint: 'CASE WHEN … THEN … WHEN … THEN … ELSE … END. Условия проверяются по порядку.', sql: "SELECT id, price, CASE WHEN price < 1000 THEN 'дёшево' WHEN price < 10000 THEN 'средне' ELSE 'дорого' END FROM products" },
      { title: 'Пол покупателей', text: 'Посчитай покупателей по полу с расшифровкой: `мужской` для `m`, `женский` для `f`, `не указан` для пустого значения. Выведи расшифровку и количество.', hint: 'CASE можно поставить в SELECT и сгруппировать по нему (GROUP BY 1).', sql: "SELECT CASE gender WHEN 'm' THEN 'мужской' WHEN 'f' THEN 'женский' ELSE 'не указан' END, COUNT(*) FROM customers GROUP BY 1" },
      { title: 'Два счётчика сразу', text: 'Одним запросом посчитай количество доставленных (`delivered`) и количество отменённых (`cancelled`) заказов — два столбца в таком порядке.', hint: 'SUM(CASE WHEN status = \'delivered\' THEN 1 ELSE 0 END).', sql: "SELECT SUM(CASE WHEN status = 'delivered' THEN 1 ELSE 0 END), SUM(CASE WHEN status = 'cancelled' THEN 1 ELSE 0 END) FROM orders" },
      { title: 'Доля промокодов', text: 'Для каждого города доставки выведи город и долю заказов с промокодом в процентах, округлённую до двух знаков. Заказы без города доставки не учитывай.', hint: 'COUNT(promo_code) считает только заказы, где промокод есть. Умножай на 100.0.', sql: 'SELECT delivery_city, ROUND(100.0 * COUNT(promo_code) / COUNT(*), 2) FROM orders WHERE delivery_city IS NOT NULL GROUP BY delivery_city' },
    ],
  },
]

// Плоский список с идентификаторами вида «where-3»
const TASKS = CATEGORIES.flatMap(c => c.tasks.map((t, i) => ({ ...t, id: `${c.id}-${i + 1}`, category: c.id })))

// Описание столбцов для подсказки в интерфейсе
const COLUMN_DOCS = {
  categories: {
    _: 'Разделы каталога: верхний уровень и подкатегории',
    id: 'идентификатор раздела',
    parent_id: 'родительский раздел; NULL у разделов верхнего уровня',
    name: 'название',
    slug: 'адрес раздела в URL',
    is_active: '1 — раздел показывается в каталоге, 0 — скрыт',
    sort_order: 'порядок вывода',
    created_at: 'дата создания (UTC)',
  },
  customers: {
    _: 'Покупатели маркетплейса',
    id: 'идентификатор покупателя',
    email: 'электронная почта',
    phone: 'телефон в том виде, как его ввели; бывает NULL',
    first_name: 'имя',
    last_name: 'фамилия; бывает NULL',
    gender: "пол: 'm', 'f' или NULL",
    birth_date: 'дата рождения (ГГГГ-ММ-ДД); бывает NULL',
    city: 'город; бывает NULL',
    registered_at: 'дата регистрации (UTC)',
    last_login_at: 'последний вход; NULL — ни разу не заходил после регистрации',
    is_verified: '1 — почта подтверждена',
    loyalty_points: 'баллы программы лояльности',
    marketing_consent: '1 — согласен на рассылки',
    deleted_at: 'когда удалил аккаунт; NULL — аккаунт активен',
  },
  products: {
    _: 'Товары каталога',
    id: 'идентификатор товара',
    sku: 'артикул',
    name: 'название',
    brand: 'бренд; бывает NULL',
    category_id: 'раздел → categories.id',
    price: 'цена, ₽',
    old_price: 'цена до скидки; NULL — скидки нет',
    stock: 'остаток на складе, шт.',
    rating: 'средняя оценка; NULL — отзывов нет',
    reviews_count: 'количество отзывов',
    weight_grams: 'вес, г; бывает NULL',
    is_active: '1 — товар продаётся, 0 — снят с продажи',
    created_at: 'дата добавления (UTC)',
    updated_at: 'дата последнего изменения; бывает NULL',
  },
  orders: {
    _: 'Заказы',
    id: 'номер заказа',
    customer_id: 'покупатель → customers.id',
    status: "статус: 'new', 'processing', 'paid', 'shipped', 'delivered', 'cancelled', 'returned'",
    payment_method: "оплата: 'card', 'sbp', 'cash', 'installments' или NULL",
    promo_code: 'промокод; NULL — без промокода',
    delivery_type: "доставка: 'pickup_point', 'courier', 'post'",
    delivery_city: 'город доставки; бывает NULL',
    items_count: 'товаров в заказе, шт.',
    subtotal: 'сумма товаров, ₽',
    discount_amount: 'скидка, ₽',
    delivery_price: 'стоимость доставки, ₽',
    total_amount: 'итого к оплате, ₽',
    comment: 'комментарий покупателя; бывает NULL',
    created_at: 'когда оформлен (UTC)',
    paid_at: 'когда оплачен; NULL — не оплачен онлайн',
    delivered_at: 'когда доставлен; NULL — ещё не доставлен',
  },
  order_items: {
    _: 'Позиции заказов: какие товары и сколько',
    id: 'идентификатор позиции',
    order_id: 'заказ → orders.id',
    product_id: 'товар → products.id',
    quantity: 'количество, шт.',
    unit_price: 'цена за штуку на момент заказа, ₽',
  },
}

module.exports = { CATEGORIES, TASKS, COLUMN_DOCS }
